

accueil:
      path: /
      controller: App\Controller\AccueilController::index 




visiteur:
      path: /visiteur
      controller: App\Controller\VisiteurController::index
      
visiteur/menu:
      path: /visiteur/menu/
      controller: App\Controller\VisiteurController::menu      
      
visiteur/consulter:      
      path: /visiteur/consulter/
      controller: App\Controller\VisiteurController::consulter
      
visiteur/saisir:      
      path: /visiteur/saisir
      controller: App\Controller\VisiteurController::saisir    
      
visiteur/saisirMois:
      path: /visiteur/saisirMois
      controller: App\Controller\VisiteurController::saisirMois        
  
  
 
      
comptable:
      path: /comptable
      controller: App\Controller\ComptableController::index
      
comptable/menu:
      path: /comptable/menu/
      controller: App\Controller\ComptableController::menu       
      
comptable/suivre:
      path: /comptable/suivre
      controller: App\Controller\ComptableController::suivre      
      
comptable/valider:
      path: /comptable/valider
      controller: App\Controller\ComptableController::valider
